version: '3.7'

services:

  instant-splat:
    build: 
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    networks:
      - main
    restart: always
    ports:
      - "7860:7860"
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              count: all
              capabilities: [gpu]

networks:
  main:
    driver: bridge
